### ISSUE TITLE
请问可以加 ikatago 群吗

### ISSUE THREAD

**Issue by yufeng97** [kinfkong/ikatago-faq#2]
感谢教程分享, 我想实现在windows上部署ikatago-server,一直没有找到什么好的教程, 文档里提到的ikatago群也搜不到, 能不能告知一下群号呢? 或者更新一下部署教程呢?
 提前感谢

**Comment by CaiNiaoGo1** [comment]
群聊【ikatago】：703409387
进群后请仔细阅读并确认收到公告，然后即可自由在群内提出问题，欢迎你的加入！

**Comment by yufeng97** [comment]
谢谢！
